// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DCJvawb-L8xY4drbn1NfZTrgOQB9T68',
    appId: '1:557681986918:web:5b412b6b9fbe3031138ca7',
    messagingSenderId: '557681986918',
    projectId: 'ecomuserdata',
    authDomain: 'ecomuserdata.firebaseapp.com',
    storageBucket: 'ecomuserdata.firebasestorage.app',
    measurementId: 'G-ZVZD11M67R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGVbq2rc3SQwBQF3yHwIRu88dPNE9CR8',
    appId: '1:557681986918:android:2e4bc5ef90a23c18138ca7',
    messagingSenderId: '557681986918',
    projectId: 'ecomuserdata',
    storageBucket: 'ecomuserdata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_9KDlgciPQ2EeM01LWAJvvYntIr3eS2A',
    appId: '1:557681986918:ios:689d0ff3f51ad271138ca7',
    messagingSenderId: '557681986918',
    projectId: 'ecomuserdata',
    storageBucket: 'ecomuserdata.firebasestorage.app',
    iosBundleId: 'com.example.ecomApi',
  );
}
